# Generated by Django 4.2.6 on 2023-10-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('login', models.ImageField(upload_to='logo_image/', verbose_name='логотип')),
                ('phone', models.CharField(max_length=200, verbose_name='телефонный номер')),
            ],
            options={
                'verbose_name': 'Основные настройки',
                'verbose_name_plural': 'Основная настройка',
            },
        ),
    ]
