# Generated by Django 4.2.6 on 2023-10-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('number', models.CharField(max_length=20, verbose_name='телефоннный номер')),
                ('info', models.TextField(verbose_name='информация')),
            ],
            options={
                'verbose_name': ('Про нас',),
                'verbose_name_plural': 'Про участника',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube', models.URLField(verbose_name='ютуб')),
                ('fasebook', models.URLField(verbose_name='фейсбук')),
            ],
            options={
                'verbose_name': ('Контакты',),
                'verbose_name_plural': 'Контакт',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_news', models.TextField(verbose_name='Последние новости')),
                ('all_news', models.TextField(verbose_name='Все новости')),
            ],
            options={
                'verbose_name': ('Новости',),
                'verbose_name_plural': 'Новост',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(verbose_name='Посты')),
            ],
            options={
                'verbose_name': ('Посты',),
                'verbose_name_plural': 'Пост',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=30, verbose_name='Команда')),
            ],
        ),
    ]
